### ISSUE TITLE
Should I commit package-lock.json?

### ISSUE THREAD

**Issue by cravtos** [antibot-dev-team/antibot-agent#8]
Sometimes after `make install`, `package-lock.json` is modified and it is not listed in `.gitignore`. 
Upon googling found this: https://stackoverflow.com/a/56254478. 

So should I commit `package-lock.json` or `make install` should do `npm ci`? 
Or I just should ignore 'modified' status of `package-lock.json`?

**Comment by cravtos** [comment]
@manmolecular

**Comment by manmolecular** [comment]
You shouldn't commit `package-lock.json` after install if you didn't add anything new in terms of packages.

Yep, `npm ci` looks ok, I'll add fix it in the `Makefile`
